### ISSUE TITLE
Could you consider renaming the extension? 🙏🏼

### ISSUE THREAD

**Issue by Jonatthu** [Penggeor/bun#4]
Bun has official support for VSCode. Almost every other language uses the language name as a single word. It would be nice if you considered renaming this extension to Bun X (whatever this extension does better or uniquely). By doing this, Bun can officially take this name and make it easier for everyone to install the right one. Please 🙏🏼🙏🏼🙏🏼🙏🏼🙏🏼🙏🏼🙏🏼🙏🏼🙏🏼🙏🏼🙏🏼

**Comment by wukaipeng-dev** [comment]
I will do if Bun team contacts me.

**Comment by RiskyMH** [comment]
> I will do if Bun team contacts me.

Hi, I'm on the Bun team and we would appreciate it if this one could be renamed so the one most people are looking for can be first!

Thanks!

**Comment by wukaipeng-dev** [comment]
@RiskyMH  How do you verify you are on the Bun team?

**Comment by RiskyMH** [comment]
> @RiskyMH  How do you verify you are on the Bun team?

A simple way is I'm in the oven-sh github organisation which only the team is in.

Another way as how I can publish the vscode extension, I can include a message.

**Comment by RiskyMH** [comment]
> @RiskyMH  How do you verify you are on the Bun team?

A simple way is I'm in the oven-sh githib organisation which only the team is in.

Another way as how I can publish the vscode extension, I can include a message.

**Comment by wukaipeng-dev** [comment]
@RiskyMH Verify you are by the second way.

**Comment by RiskyMH** [comment]
@Penggeor I put your message at bottom of the readme.

https://marketplace.visualstudio.com/items?itemName=oven.bun-vscode

**Comment by wukaipeng-dev** [comment]
@Jonatthu  Check! I need two things:
- A formal mail to request a rename from Bun's official mail account.
- Leave the explanation in your VSCode extension README.

**Comment by Jonatthu** [comment]
@Penggeor, how about if the creator of Bun comments here about how nice it is for you to do this?

This doesn't require official emails or mods to the readme. Also, it benefits your extension to be more explicit on what truly specializes on, all of this is optional and for the love of your community. 

You are not obligated to do this. You would just be showing support back to Bun by doing this 🥇 
In reality, this is just for the community, I hope you don't feel this is a hostile request 🙏🏼. 

A cool rename could be "Bun Tools" or "Bun Extension Tools"

If you notice many languages have this pattern:

<img width="330" alt="image" src="https://github.com/user-attachments/assets/c88cd310-c0ad-4979-8b2a-25da05fd4517">
<img width="330" alt="image" src="https://github.com/user-attachments/assets/b0e77a78-04fc-425c-9c0a-260e3bdc4bd1">
<img width="330" alt="image" src="https://github.com/user-attachments/assets/f9b7eebe-89f3-483d-a235-d78f60a03800">

**Comment by wukaipeng-dev** [comment]
You could contemplate deeply why the two aforementioned things are needed.
